# fly.toml app configuration file generated for vl-outline-wiki on 2025-09-05T11:52:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vl-outline-wiki'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'
  [build.args]
    NODE_VERSION= "20.0.0"
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
