app = 'vl-outline-wiki'
primary_region = 'cdg'

[build]
  [build.args]
    NODE_VERSION= "20.0.0"
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
